### ISSUE TITLE
получение данных по тикеру - т.к. API обновился

### ISSUE THREAD

**Issue by WISEPLAT** [DBoyara/FinamTradeApiPy#22]
Добрый день! 
Будет ли обновление библиотеки с асинхронным получением данных по тикеру? т.к. API у Финама обновился..
Можно ли  ASAP? )))

**Comment by DBoyara** [comment]
Добрый день! А о каком методе идет речь? Не нашел обновлений апишки

**Comment by DBoyara** [comment]
Посмотрел доку, нового ничего не нашел. Если что приходите с конкретным примером
