### ISSUE TITLE
Теряется важная информация из запроса по портфелю!!!!!

### ISSUE THREAD

**Issue by publine2** [DBoyara/FinamTradeApiPy#30]
Теряется важная информация из запроса по портфелю!!!!!

Не могли бы Вы изменить класс (в файле finam_trade_api/portfolio/model.py)

class Position(BaseModel):
    securityCode: str
    market: str
    balance: int
    currentPrice: int
    equity: int
    averagePrice: int
    currency: str
    accumulatedProfit: int
    todayProfit: int
    unrealizedProfit: int
    profit: int
    maxBuy: int
    maxSell: int
    priceCurrency: str
    averagePriceCurrency: str
    averageRate: int

на вот такой класс:

class Position(BaseModel):
    securityCode: str
    market: str
    balance: int
    currentPrice: float
    equity: float
    averagePrice: float
    currency: str
    accumulatedProfit: float
    todayProfit: float
    unrealizedProfit: float
    profit: float
    maxBuy: int
    maxSell: int
    priceCurrency: str
    averagePriceCurrency: str
    averageRate: float

**Comment by DBoyara** [comment]
Спасибо! Не пользуюсь методами портфеля, поэтому пропустил, сегодня сделаю

**Comment by DBoyara** [comment]
Готово, версия v2.1.0
