### ISSUE TITLE
В классе OrderResponse  не хватает полей securityBoard и market

### ISSUE THREAD

**Issue by publine2** [DBoyara/FinamTradeApiPy#32]
В классе OrderResponse(BaseModel) (файл finam_trade_api/order/model.py)
не хватает полей securityBoard и market, оба текстовые.

Также буду благодарен, если подскажите, как попроще можно узнать реальную цену по которой был исполнен ордер.
На данный момент ничего умнее не придумал кроме как два раза вызывать портфолио(один раз перед ордером и второй раз по исполнении),
и на базе портфолио всякими правдами и неправдами вычислять эту цену.

**Comment by DBoyara** [comment]
Поля добавлю на выходных.

На сколько я помню метод [OrderClient.get_orders](https://github.com/DBoyara/FinamTradeApiPy/blob/master/finam_trade_api/order/order.py#L30) с параметром [includeMatched = "true"](https://github.com/DBoyara/FinamTradeApiPy/blob/master/finam_trade_api/order/model.py#L53) выдаст исполеннные заявки, у которых поле price будет ценой исполненния.

**Comment by publine2** [comment]
Очень хотелось бы, но к сожалению нет. OrderClient.get_orders выдает  цену указанную при выставлении ордера, а не ту по которой реально ордер был исполнен. И это связано не с вашим кодом, а с сервером финам апи - именно он возвращает цену запроса а не цену исполнения. Если хотите - можете проверить сами, выставьте ордер на покупку по цене заранее более высокой чем рыночная, и после исполнения ордера можете на него посмотреть, там будет ваша изначальная цена, а не та по которой выполнится ордер:
curl -X 'GET' 'https://trade-api.finam.ru/public/api/v1/orders?clientId=XXXXXXX&IncludeMatched=true&IncludeCanceled=true&IncludeActive=true' -H 'accept: text/plain' -H 'X-Api-Key: XXXXXXXXXXXXXXXX'

Я уже писал им письмо, но ответа нет.

**Comment by DBoyara** [comment]
можно обновиться до версии 2.1.1. 

А на счет вопроса про цену исполнения заявки, можно написать в их [репозитории](https://github.com/FinamWeb/trade-api-docs), они иногда отвечают
